[package]
name = "monopolize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
clap_derive = "4.5.8"
thiserror = "1.0.63"
parquet = "52.1.0"
